In [1]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


In [2]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.18181818 1.        ]]
[[4.         1.         2.        ]
 [0.         2.75       3.5       ]
 [0.         0.         1.36363636]]


In [3]:
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)

[[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


In [4]:
A = np.array([[0,1,1],[2,1,0],[3,4,5]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0.+0.j  1.+0.j  1.+0.j]
 [ 2.+0.j  1.+0.j -0.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]
[ 5.85410197+0.j -0.85410197+0.j  1.        +0.j]


In [5]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [6]:
# If you know the eigenvalues must be real
# because A is a positive definite (e.g. covariance) matrix
# use real_if_close

A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)

[ 5.85410197+0.j -0.85410197+0.j  1.        +0.j]


In [7]:
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

array([1., 1., 1., 1.])

In [8]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)

array([-2.34 ,  9.745, -4.85 , -1.34 ])

In [9]:
U, s, V = np.linalg.svd(A)
print(s)
print(max(s)/min(s))

[15.54574383  6.90016811  3.83634007  0.00486006]
3198.6725811992283
