In [1]:
import numpy as np
import pandas as pd
#三變數方程式
A= [[1,-2,3],[-1,3,0],[2,-5,5]] #輸入A矩陣
A= np.array(A) #np
b= [9,-4,17] #輸入B矩陣
b= np.array(b) #np
b= b.reshape(3,1) #重塑成3列1行
x= np.linalg.solve(A, b) #解答
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [2]:
np.linalg.inv(A)@b #驗算

array([[ 1.],
       [-1.],
       [ 2.]])

In [3]:
#五變數方程式 

n=5


np.random.seed(0) #隨機參數

A= np.random.randint(-5,5,size=(n,n)) #5*5矩陣

 
np.random.seed(1) 

b= np.random.randint(-5,5,size=(n,1)) #5*1矩陣

x= np.linalg.solve(A, b) #運算

print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 
np.linalg.inv(A)@b #驗算

 

n= 5,  

A= [[ 0 -5 -2 -2  2]
 [ 4 -2  0 -3 -1]
 [ 2  1  3  3 -4]
 [ 1  2  2  3 -4]
 [ 0  4  3  4 -1]] 

b= [[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]] 

x= [[-5.05357143]
 [-1.75      ]
 [ 7.30357143]
 [-5.66071429]
 [-2.73214286]] 




array([[-5.05357143],
       [-1.75      ],
       [ 7.30357143],
       [-5.66071429],
       [-2.73214286]])

In [4]:
#十變數方程式 

n=10


np.random.seed(1)#隨機參數

A= np.random.randint(-5,5,size=(n,n)) #10*10矩陣

 
np.random.seed(5)#隨機參數

b= np.random.randint(-5,5,size=(n,1)) #10*1矩陣

x= np.linalg.solve(A, b) #運算

print( 

f''' 

n= {n},  

A= {A} 

b= {b} 

x= {x} 

''') 
np.linalg.inv(A)@b #驗算

 

n= 10,  

A= [[ 0  3  4  0 -5 -5 -4  2  1  4]
 [-3 -1  0 -3 -1 -3 -1  2  2  4]
 [-4  2 -5  1  4  4  2  1  4 -4]
 [-5 -4  3  3 -2  4  3  2 -2  1]
 [ 0 -4  4 -2 -1  3 -4 -1 -5 -2]
 [ 4 -3 -5 -1  4 -3  2  2  4  3]
 [ 1  4 -2  2  2 -1  0  4 -2  1]
 [ 3 -5 -3  2  2  4  2 -2 -5  3]
 [ 2  2 -4 -4 -2 -5  3  1 -1  0]
 [ 1 -3  0  2  3 -1 -1  2  2 -1]] 

b= [[-2]
 [ 1]
 [ 1]
 [-5]
 [ 4]
 [ 3]
 [-1]
 [ 2]
 [-5]
 [-5]] 

x= [[ 1.34701608]
 [ 0.93920126]
 [ 0.91827119]
 [-2.1209692 ]
 [ 0.59519967]
 [ 2.51647156]
 [-0.06057342]
 [ 0.44725952]
 [ 0.87600885]
 [ 1.26371152]] 




array([[ 1.34701608],
       [ 0.93920126],
       [ 0.91827119],
       [-2.1209692 ],
       [ 0.59519967],
       [ 2.51647156],
       [-0.06057342],
       [ 0.44725952],
       [ 0.87600885],
       [ 1.26371152]])